### ISSUE TITLE
Version 1.1.0 not on packagist

### ISSUE THREAD

**Issue by Benjamin-K** [sandstorm/NeosTwoFactorAuthentication#16]
The new version with the option to enforce 2FA is not (yet) available on packagist. Maybe there is some sync error. Could you please check and fix this so we can update to the new version without adding this repo as a composer repository?

See https://packagist.org/packages/sandstorm/neostwofactorauthentication 

@JamesAlias, @Pingu501 

BTW: Thanks for your great work on this!

**Comment by JamesAlias** [comment]
The package is on "auto update" in packagist and that takes some time (i guess it's daily).

Anyways, I just updated it manually and it should be available now.
Have fun 🙂
