### ISSUE TITLE
Incompatible with PHP < 8

### ISSUE THREAD

**Issue by bwaidelich** [sandstorm/NeosTwoFactorAuthentication#2]
Hi,

the composer manifest claims that this package is compatible with PHP 7.4, but it is not (see https://github.com/sandstorm/NeosTwoFactorAuthentication/blob/e58561bf3dedf5ea08c4999a0e4a03de264a0728/Classes/Domain/Model/Dto/SecondFactorDto.php#L24 for example).

Great package by the way! :)

**Comment by Pingu501** [comment]
Hey @bwaidelich 

glad you like this package! You are totally right, this is php8 syntax. Fixed this and did a release. With version `1.0.1` this is fixed :)
