### ISSUE TITLE
Document list of compatible 2FA apps

### ISSUE THREAD

**Issue by Sebobo** [sandstorm/NeosTwoFactorAuthentication#4]
While testing I could only successfully use the plugin with the `Google Authenticator`, the Microsoft and 1Password said that the QR Code is invalid.

Would be great to add a "tested" app list to the readme.

**Comment by Benjamin-K** [comment]
I tested this and think, this is a bug on iOS only.

Android:

- Google Authenticator ✅
- Microsoft Authenticator ✅
- Authy ✅

iOS:

- Google Authenticator ✅
- Microsoft Authenticator ❌
- Authy ✅

**Comment by Benjamin-K** [comment]
Maybe this can be fixed by showing the Authentication Code as string (which is not the best / user friendliest way), as almost all 2FA apps allow adding an account by manually entering the code.

**Comment by Sebobo** [comment]
My 1PW on MacOS also declined the QR code

**Comment by Pingu501** [comment]
Hey, thx for already creating this list! :)
Just added it to the README and will now check, why 1Password and Microsoft Authenticator do not work ;)

**Comment by Pingu501** [comment]
Found the issue! There was missing URL encoding for the issuer. Fixed with [7b6c5ef](https://github.com/sandstorm/NeosTwoFactorAuthentication/commit/7b6c5ef4d70ef4874ad8c23f5cb7ae1f2737911c)

Going to tag a release now, will be fixed with version `1.0.3`

**Comment by Sebobo** [comment]
Awesome, thx for fixing this so quickly.
