### ISSUE TITLE
2FA-Token becomes invalid

### ISSUE THREAD

**Issue by Benjamin-K** [sandstorm/NeosTwoFactorAuthentication#7]
We have a Neos 5.3 installation using this plugin. In some cases the 2FA token becomes invalid and the users are unable to login again. We can't reproduce this yet and don't know why this happens. Once the token becomes invalid it stays invalid. 
Do you have any idea, why this could happen?

**Comment by Pingu501** [comment]
Hey @Benjamin-K!
Sounds really weird. The OTP is based on the system time, did something changed there? Can you tell me which php version you are using?

**Comment by Benjamin-K** [comment]
Maybe #9 could be the reason for this and this issue will then be fixed with #10, too.

**Comment by Benjamin-K** [comment]
@Pingu501 
Didn't have this for a long time. But i think the issue really comes from navigation to `/neos/login` directly. Whenever you navigate to `/neos` only (which redirects to `/neos/login`), this issue does not exist – at least for me. 

I'll close this for now and will reopen it, if the issue returns.
